apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-github-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShivamMudotia/argocd-apps.git
    targetRevision: HEAD
    path: sock-shop  # Change to the folder where your Kubernetes YAML files exist
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
